version: "3.9"

services:
  pilipili_frontend:
    image: hsuyelin/pilipili_frontend:latest
    container_name: ${CONTAINER_NAME:-pilipili_frontend}
    environment:
      - UID=0
      - GID=0
      - GIDLIST=0
      - TZ=Asia/Shanghai
    volumes:
      - ./config/config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    privileged: true
    network_mode: host